### ISSUE TITLE
Unchecking everything results in unwanted behaviour

### ISSUE THREAD

**Issue by ErinvanderVeen** [ErinvanderVeen/BootstrapEditor#1]
Deselecting all checkboxes results the content of the column being shown as plaintext.

**Comment by camilstaps** [comment]
The reason that they are normally not shown in plaintext is that bootstrap-theme is used. Without that, everything is shown in plaintext anyway. This therefore doesn't need to be fixed in this project.

End users can add another class to every cell if they want to add the same layout to every cell.
