### ISSUE TITLE
Apply updates directly

### ISSUE THREAD

**Issue by camilstaps** [ErinvanderVeen/BootstrapEditor#3]
Would it be a lot of work to
- Remove the <kbd>apply</kbd> and <kbd>cancel</kbd> buttons
- Apply changes in the form directly

? I think this could ease UI because otherwise you need to click apply every time you change something and right click again if you are not satisfied.

**Comment by ErinvanderVeen** [comment]
I thought of this, but it could result in a situation where the menu would hover over a column to which it does not belong.

E.g. You right click the left most column, and downsize it which makes middle column shift left. Now the custom-menu is over the middle column. But changes applied to the menu will still result in changes to the left most column.

I don't know what behavior is most desired.

And no, I don't think it would be a lot of work.
